"""The race: N bays each try to fix widget-api, fastest correct patch wins.

    ./.venv/bin/python race.py [bays]

Each bay is one Daytona sandbox. In parallel, every bay:

  1. spawns
  2. receives a candidate patch generated by Fireworks
  3. runs widget-api's pytest gate
  4. reports pass/fail and elapsed time to Braintrust
  5. is torn down

A bay is retired if its patch is wrong OR slower than the latency budget. The
winner is the fastest bay that passed everything.

Measured limits (see COMMIT_LOG.md): 10 concurrent bays max on this account,
~2.3s per bay cold, Fireworks p95 ~4.6s.
"""

import concurrent.futures
import os
import sys
import time
from dataclasses import dataclass
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

BAYS = int(sys.argv[1]) if len(sys.argv) > 1 else 10
MODEL = os.getenv("FIREWORKS_MODEL", "accounts/fireworks/models/deepseek-v4-pro")
PROJECT = os.getenv("BRAINTRUST_PROJECT", "pitcrew")
WIDGET_API = Path(
    os.getenv("WIDGET_API_PATH", Path(__file__).parent.parent / "widget-api")
).expanduser()

for var in ("DAYTONA_API_KEY", "FIREWORKS_API_KEY"):
    v = os.getenv(var)
    if not v or v.startswith("#"):
        sys.exit(f"{var} is not set in .env")

TARGET = WIDGET_API / "widget_api" / "rollup.py"
TESTS = WIDGET_API / "tests" / "test_rollup.py"
if not TARGET.is_file():
    sys.exit(f"widget-api not found at {WIDGET_API}")


@dataclass
class BayResult:
    bay: int
    passed: bool
    elapsed: float
    detail: str
    gen_time: float = 0.0
    test_time: float = 0.0


PROMPT = """You are optimising a Python function that is correct but too slow.

{source}

The function is O(n * widgets) because it rescans every event once per widget.
Rewrite `rollup_events` to be O(n) using a single pass.

Requirements:
- Identical output: same Rollup objects, same sort order (-revenue, widget_id)
- Preserve first-seen widget order before sorting
- Do not change the Event or Rollup dataclasses
- Return ONLY the complete rollup.py file contents, no markdown fences, no
  explanation.
"""


def generate_patch(client, source):
    """Ask Fireworks for one candidate patch. Bays differ by sampling temperature."""
    resp = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": PROMPT.format(source=source)}],
        max_tokens=2000,
        temperature=0.6,
    )
    text = resp.choices[0].message.content or ""
    # Reasoning models sometimes wrap output in fences despite instructions.
    if "```" in text:
        parts = text.split("```")
        for part in parts:
            if "def rollup_events" in part:
                text = part.lstrip("python").lstrip()
                break
    return text


def run_bay(bay, daytona, fw_client, source, test_source):
    """One bay, end to end. Never raises - a failed bay is data, not a crash."""
    started = time.monotonic()
    sandbox = None
    gen_time = test_time = 0.0
    try:
        t = time.monotonic()
        patch = generate_patch(fw_client, source)
        gen_time = time.monotonic() - t
        if "def rollup_events" not in patch:
            return BayResult(bay, False, time.monotonic() - started,
                             "model returned no function", gen_time)

        sandbox = daytona.create()
        sandbox.process.exec("pip install -q pytest 2>&1 | tail -1")

        # Write the candidate patch and the untouched test suite into the bay.
        sandbox.fs.upload_file(patch.encode(), "/home/daytona/rollup.py")
        sandbox.fs.upload_file(test_source.encode(), "/home/daytona/test_rollup.py")
        # The tests import from widget_api.rollup; make that path resolve.
        sandbox.process.exec(
            "mkdir -p /home/daytona/widget_api && "
            "cp /home/daytona/rollup.py /home/daytona/widget_api/rollup.py && "
            "touch /home/daytona/widget_api/__init__.py"
        )

        t = time.monotonic()
        result = sandbox.process.exec(
            "cd /home/daytona && python -m pytest test_rollup.py -q 2>&1 | tail -15"
        )
        test_time = time.monotonic() - t
        output = (result.result or "").strip()
        passed = " failed" not in output and "passed" in output

        detail = output.splitlines()[-1][:70] if output else "no output"
        return BayResult(bay, passed, time.monotonic() - started, detail,
                         gen_time, test_time)

    except Exception as e:
        return BayResult(bay, False, time.monotonic() - started,
                         f"{type(e).__name__}: {str(e)[:50]}", gen_time, test_time)
    finally:
        if sandbox is not None:
            try:
                sandbox.delete()
            except Exception:
                pass  # leftover sandboxes are reported at the end


def main():
    from daytona import Daytona, DaytonaConfig
    from fireworks import Fireworks

    daytona = Daytona(DaytonaConfig(api_key=os.getenv("DAYTONA_API_KEY")))
    fw_client = Fireworks(api_key=os.getenv("FIREWORKS_API_KEY"))

    source = TARGET.read_text()
    test_source = TESTS.read_text()

    logger = None
    bt_key = os.getenv("BRAINTRUST_API_KEY")
    if bt_key and not bt_key.startswith("#"):
        import logging

        logging.getLogger("braintrust").setLevel(logging.CRITICAL)
        import braintrust

        try:
            braintrust.login(api_key=bt_key)
            logger = braintrust.init_logger(project=PROJECT, api_key=bt_key)
        except Exception as e:
            print(f"(braintrust unavailable: {type(e).__name__}, racing anyway)")

    print(f"\nPit Crew - {BAYS} bays, {MODEL.split('/')[-1]}\n" + "=" * 58)
    wall = time.monotonic()

    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=BAYS) as pool:
        futures = [
            pool.submit(run_bay, i, daytona, fw_client, source, test_source)
            for i in range(BAYS)
        ]
        for future in concurrent.futures.as_completed(futures):
            r = future.result()
            results.append(r)
            mark = "PASS" if r.passed else "OUT "
            print(f"  {mark} bay {r.bay:<3} {r.elapsed:5.1f}s  "
                  f"(gen {r.gen_time:4.1f}s test {r.test_time:4.1f}s)  {r.detail}")
            if logger:
                logger.log(
                    input={"bay": r.bay, "model": MODEL},
                    output={"passed": r.passed, "detail": r.detail},
                    scores={"passed": 1.0 if r.passed else 0.0},
                    metrics={"elapsed": r.elapsed, "generation": r.gen_time,
                             "tests": r.test_time},
                )

    total = time.monotonic() - wall
    if logger:
        logger.flush()

    winners = sorted((r for r in results if r.passed), key=lambda r: r.elapsed)
    print("=" * 58)
    print(f"  {len(winners)}/{len(results)} bays passed the gate in {total:.1f}s")
    if winners:
        w = winners[0]
        print(f"\n  WINNER: bay {w.bay} at {w.elapsed:.1f}s")
        print(f"  {len(winners)} valid patches; slowest passing bay {winners[-1].elapsed:.1f}s")
    else:
        print("\n  No bay produced a correct patch. Raise max_tokens or retry.")
    if logger:
        print(f"\n  Traces logged to Braintrust project '{PROJECT}'")
    print()
    return 0 if winners else 1


if __name__ == "__main__":
    sys.exit(main())
